# ──────────────────────────────────────────
# application.yml
# Place this in the same folder as Lavalink.jar
# ──────────────────────────────────────────

server:
  port: 2333

# ── CORE LAVALINK CONFIG ───────────────────
lavalink:
  server:
    password: "Grizzly101*"    # must match your bot’s Manager config
    sources:
      youtube: false           # disable the deprecated built-in
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      mixer: true
      http: true
      local: false

  # Let Maven pull in the YouTube-Source plugin automatically
  plugins:
    - dependency: "dev.lavalink.youtube:youtube-plugin:0e5cfca4e88c32db430ce76e6866b13035c85d22"
      snapshot: true

# ── YOUTUBE-SOURCE PLUGIN CONFIG ─────────
# All settings for the youtube-plugin go here.
plugins:
  youtube:
    enabled: true              # turn the plugin on
    allowSearch: true          # enable "ytsearch:" queries
    allowDirectVideoIds: true  # allow raw /watch?v= links
    allowDirectPlaylistIds: true

    # ONLY OAuth-compatible clients here:
    clients:
      - TV                     # supports OAuth
      - TVHTML5EMBEDDED        # also supports OAuth

    oauth:
      enabled: true
      skipInitialization: true # don’t prompt again—using your token
      refreshToken: "Token"
 