const wordBlacklist = [
  "discord.gg/",
  "discordapp.com/invite/",
  "discord.com/invite/",
  "discord.me/",
  "discord.io/",
  "discord.tk/",
  "discord.gift/",
  "discordapp.com/gifts/",
  "discord.com/gifts/",
  "discord.gifts/",
  "nigger",
  "nigga",
  "faggot",
  "fag",
  "niglet",
  "spic",
  "chink",
  "niggle",
  "coon",
  "kill yourself",
  "nig",
];

module.exports = wordBlacklist;
